### ISSUE TITLE
where is ubuntu_sshd_gcc_gerry:14.04?

### ISSUE THREAD

**Issue by fangjj** [gerryyang/mac-utils#1]
我在使用你的nginx_ubuntu的Dockerfile遇到问题。
FROM ubuntu_sshd_gcc_gerry:14.04
在dockerhub 上构建报错：Error: image library/ubuntu_sshd_gcc_gerry:14.04 not found
直接换成FROM Ubuntu:14.04?

**Comment by gerryyang** [comment]
是的，我使用的自己的私有镜像派生的，便于集成一些已有的功能，你修改为官方的镜像即可。

**Comment by pandashuai** [comment]
用 官方的镜像 apt-get install -y nginx 失败！

**Comment by gerryyang** [comment]
@pandashuai 如果使用官方的镜像建议使用国外的VPS，推荐使用DigitalOcean
